package com.prakash.busi.model;
// default package
// Generated Jul 1, 2017 3:33:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * LCategory generated by hbm2java
 */
@Entity
@Table(name = "l_category", catalog = "business")
public class LCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long categoryid;
	private Integer version;
	private Long busitypeid;
	private String categoryname;
	private Date createddate;
	private Date lastupdateddate;
	private String description;
	private Long createdby;
	private Long updatedby;
	private Long parentid;
	private Set<TProductinfo> TProductinfos = new HashSet<TProductinfo>(0);

	public LCategory() {
	}

	public LCategory(long categoryid) {
		this.categoryid = categoryid;
	}

	public LCategory(long categoryid, Long busitypeid, String categoryname,
			Date createddate, Date lastupdateddate, String description,
			Long createdby, Long updatedby, Long parentid,
			Set<TProductinfo> TProductinfos) {
		this.categoryid = categoryid;
		this.busitypeid = busitypeid;
		this.categoryname = categoryname;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.description = description;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.parentid = parentid;
		this.TProductinfos = TProductinfos;
	}

	@Id
	@Column(name = "categoryid", unique = true, nullable = false)
	public long getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(long categoryid) {
		this.categoryid = categoryid;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "busitypeid")
	public Long getBusitypeid() {
		return this.busitypeid;
	}

	public void setBusitypeid(Long busitypeid) {
		this.busitypeid = busitypeid;
	}

	@Column(name = "categoryname", length = 50)
	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "createdby")
	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Long getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Long updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "parentid")
	public Long getParentid() {
		return this.parentid;
	}

	public void setParentid(Long parentid) {
		this.parentid = parentid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LCategory")
	public Set<TProductinfo> getTProductinfos() {
		return this.TProductinfos;
	}

	public void setTProductinfos(Set<TProductinfo> TProductinfos) {
		this.TProductinfos = TProductinfos;
	}

}
